### ISSUE TITLE
Very long strings

### ISSUE THREAD

**Issue by gotev** [gotev/localiser#118]
Current state of the art translated keys are limited to [`500` characters](https://github.com/gotev/localiser/blob/master/localiser-ui/database/models.py#L119)

This has been done on purpose because:
- the whole strings table on both iOS and Android gets loaded at the app startup. Having a big string table has performance penalties, so limiting strings length is good because in turn you start thinking about solving your problems with shorter strings and you are performance-first by design
- on some older android devices, having strings longer than 500 characters crashed the app

However, nothing in this world remains unchanged for a long period of time and things must evolve. Made some research.
- On Android the new limit seems to be 32K: https://brightinventions.pl/blog/string-too-large-in-android-resources
- On iOS no apparent limitation is applied on `Localizable.strings` file nor single string's length

So given that:
- Increasing the max length for translatable strings won't cause crashes
- memory footprint of apps will tend to be greater

It could be safe to extend this limit in the next localiser release.

**Comment by skyparentile** [comment]
Lato iOS:  Localisable.string alla fine è un file che estende String (String.LocalizationValue) quindi non dovrebbe avere limiti di lunghezza:
reference apple: https://developer.apple.com/documentation/swift/string/localizationvalue?changes=_6
AppleDev forum in cui confermano nessun limite: https://developer.apple.com/forums/thread/655197 (edited)

**Comment by gotev** [comment]
String length extended from `500` to `2048`. Released in Localiser `2.3.0`.
